# **Artificial Neural Network**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__


'2.8.2'

In [ ]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
ann=tf.keras.models.Sequential()


In [ ]:
ann.add(tf.keras.layers.Dense(units=6 ,activation="relu"))    #input layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6 ,activation="relu"))    #hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))   #output layer

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5531 - accuracy: 0.7809
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4706 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4391 - accuracy: 0.8081
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4240 - accuracy: 0.8171
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4152 - accuracy: 0.8219
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4085 - accuracy: 0.8231
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4014 - accuracy: 0.8239
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3921 - accuracy: 0.8340
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3801 - accuracy: 0.8440
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3701 - accura

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


In [ ]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1530   65]
 [ 215  190]]


0.86